### ISSUE TITLE
Seção 10

### ISSUE THREAD

**Issue by jrmfilho34** [jrmfilho34/Vue-curso#10]
- [x] 149. Introdução do módulo - 04:22
- [x] 150. Configurar projeto - 03:28 - 07:50
- [x] 151. Componente lista de tarefas #01 - 03:36 - 11:26
- [x] 152. Componente tarefa #01 -06:57 - 18:23
- [x] 153. Componente Lista de tarefas #02 - 02:50 - 21:13
- [x] 154. Componente nova tarefa #01 - 09:42 - 30:55
- [x] 155. Componente nova tarefa #02 - 03:06 - 34:01
- [x] 156. Componente tarefa #02 - 08:43 - 42:44
- [x] 157. Componente tarefa #03 - 04:05 - 46:49
- [x] 158. Componente progresso - 06:26 - 53:15
- [x] 159. Usando Local Storage - 07:00 - 60:15
- [x] 160. Conclusão de módulo - 01:44 - 61:59
- [x] 161. Recursos adicionais
