### ISSUE TITLE
Seção 2

### ISSUE THREAD

**Issue by jrmfilho34** [jrmfilho34/Vue-curso#2]
- [x] Seção: 2
  - [x] 10. Introdução - 00:37
  - [x] 11. Entendendo VueJs Templates - 04:29
  - [x] 12. Sintaxe de Template e Instância VueJs trabalhando juntos - 04:21
  - [x] 13. Acessando dados da instância vuejs - 03:06 
  - [x] 14. Binding de atributos - 05:07
  - [x] 15. Entendendo e usando diretivas - 02:50
  - [x] 16. Evitando Re-Renderização com v-once - 02:49
  - [x] 17. Como imprimir HTML puro - 04:09
  - [x] 18. Hora de praticar - template - 02: 42
  - [x] 19. Hora de praticar - template (resposta) - 08:38
  - [x] 20. Escutando eventos 04:20
  - [x] 21. Obtendo dados do evento 05:29
  - [x] 22. Passando nosso próprios argumentos com eventos - 05:29
  - [x] 23. Modificadores de eventos -  06:39
  - [x] 24. Eventos de teclado - 03:20
  - [x] 25. Hora de praticar - eventos 01:17
  - [x] 26. Hora de praticar - eventos (resposta) - 05:30
  - [x] 27. Código Java script no template - 03:42
  - [x] 28. Usando two-way-binding - 04:15
  - [x] 29. Propriedades computadas - 09:17
  - [x] 30. Monitorando as mudanças - 04:37
  - [x] 31. Sintaxe reduzida (Shoethands) - 02:33
  - [x] 32. Hora de praticar - propriedades reativas - 01:36
  - [x] 33. Hora de praticar - propriedades reativas - resposta 03:03
  - [x] 34. Estilo dinâmico e classe CSS#01 - 04:56
  - [x] 35. Estilo dinâmico e classe CSS#02 - 01:52
  - [x] 36. Estilo dinâmico e classe CSS#03 - 04:33
  - [x] 37. Estilo dinâmico sem classes CSS - 05:50
  - [x] 38. Hora de praticar : estilo - 03:03
  - [x] 39. Hora de praticar: estilo - 03:03
  - [x] 40. conclusão do modulo - 00:44
