### ISSUE TITLE
Seção 8

### ISSUE THREAD

**Issue by jrmfilho34** [jrmfilho34/Vue-curso#8]
- [x] 113. Introdução ao módulo - 00:49
- [x] 114. Comunicação entre componentes - 04:06
- [x] 115. Comunicação direta com props #01 - 03:37
- [x] 116. Comunicação direta com props #02 - 01:29
- [x] 117. Nome das propriedades são case-sensitive - 03:08
- [x] 118. Usando props no componente filho - 03:21
- [x] 119. Validando props #01 - 07;34
- [x] 120. Validando props #02 - 01:40
- [x] 121. Comunicação indireta com eventos personalizados - 08:14
- [x] 122. Comunicação indireta com calback - 03:37
- [x] 123. Problema da comunicação entre componentes irmãos - 06:54
- [x] 124. Comunicação entres componentes irmãos 06:54
- [x] 125. Usando EventBus para comunicação entre componentes irmãos #01 -02:23
- [x] 126. Usando EventBus para comunicação entre componentes irmãos #01 -05:28
- [x] 127. Adicionando métodos no Event Bus - 02:49
- [x] 128. Hora de praticar: comunicação entre componentes - 01:24
- [x] 129. Hora de praticar: comunicação entre componentes (resposta) - 06:24
- [x] 130. Props por valor vs props por referência - 05:07
- [x] 131. Conclusão do módulo
- [x] 132. Recursos adicionais
